### ISSUE TITLE
Create basic documentation

### ISSUE THREAD

**Issue by sebas5384** [choko-org/redux-boot#15]
- [x] Example using handlers at README.md

---

- [x] Introduction
- [x] -- Motivation
- [x] -- Principles
- [x] Basics
- [x] -- Modules
- [x] -- Actions
- [x] -- Reducers
- [x] ---- pure reducer
- [x] ---- Action handlers
- [x] -- Middlewares
- [x] ---- pure middleware
- [x] ---- Middleware handlers
- [x] -- Side-effects
- [x] ---- Sync
- [x] ---- Async

**Comment by recidive** [comment]
1. Introduction
  1. Motivation
  2. Principles

2. Basics
  1. Modules
  2. Reducers
    1. pure reducer
    2. Action handlers
  3. Middlewares
    1. pure middleware
    2. Middleware handlers
  4. Side-effects
    1. Sync
    2. Async

[later...]

3. Recipes
  1. Immutable state
  2. Async REST request
  3. Chaining async middlewares

**Comment by sebas5384** [comment]
**Middlewares:**

Simple:
```js
const API_REQUEST = 'mymodule/api/REQUEST'
const mymodule = {
  middleware(store) {
    return next => action => {
      
      if (action.type == API_REQUEST) {
        console.log(action.payload.body, 'Api request');
      }

      return next(action)
    }
  }
}
```

**Comment by sebas5384** [comment]
Side-effect after and after an action is done https://github.com/choko-org/redux-boot/commit/8298643e8dc2596702b8597a8d17ee7b287a71cd.

**Comment by sebas5384** [comment]
@recidive and @jardix22 what do you say guys? can we close this one?

https://choko.gitbooks.io/redux-boot

**Comment by sebas5384** [comment]
@recidive I think is just missing the Actions topic.
