### ISSUE TITLE
GPL is an inappropriate license

### ISSUE THREAD

**Issue by jahewson** [choko-org/redux-boot#25]
The GPL is an inappropriate license for a library, especially a JavaScript library. Anyone who uses redux-boot is required to release their code under a GPL-compatible license. This all but guarantees that pretty much nobody will adopt your library.

This requirement is explained clearly in the [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem):

> if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing.

Given that Redux uses the MIT license, you should stick with that. It's more permissive than the GPL and will encourage other developers to actually use your library.

**Comment by recidive** [comment]
Hello @jahewson, this is an interesting topic. We had [a conversation](https://github.com/choko-org/redux-boot/issues/2) on this during one of our nightly sprints. Personally for me, this is not a concern. It's good to have the chance to revisit this topic.

Let discuss this a little bit further before taking action. We know the LGPL is the GPL compatible license more appropriate for libraries, what do you think would be the implications of using a LGPL license on a Redux extension module?

Thanks for the feedback.

**Comment by sebas5384** [comment]
@jahewson it's good to hear feedback about this issue, because to me is a great deal, I think its because I "came" from GNU/Linux and Drupal community.

Like @recidive said we had discuss this issue, and it seemed OK to release it with the GPL license, but MIT it really seems more appropriated given the context here, which is "a javascript library" and most of the libraries are with the MIT license.

I understand your point, and your are right MIT seems more appropriated.

What about LGPL ?

@jahewson probably we are going toward MIT, but I was wondering if your concerns aren't resolved with the LGPL license.

**Comment by jahewson** [comment]
@recidive, LGPL is indeed appropriate for libraries, but it brings with it some requirements which are it's not usually possible satisfy for JavaScript applications. For example, the "combined work" is required to be assembled in such a way that the LGPL'd library can be switched-out for a version built by the user. For desktop software, that means using a .so, .dll, or .dylib for dynamic linking or providing the .o files of the non-GPL'd portion for static linking. But in the world of minified JavaScript, it's going to require the full source code to the application - because the "combined work" is built and linked as a monolithic whole.

So the LGPL isn't going to work well either. Given that Redux is MIT-licensed, why bring a new license into the equation at all?

@sebas5384, that link is really talking about dual-licensing under the LGPL, which is fine - but there needs to be more than just the LGPL as the license, as on it's own it's too restrictive for modern JavaScript for the reasons I mention above.

**Comment by sebas5384** [comment]
Dual license looks like a good fit, but also an overload to redux-boot early stages.

Let's change to MIT then!

@jahewson thanks for your help o/
