### ISSUE TITLE
redux-actions newest versions require defaultState at handleAction

### ISSUE THREAD

**Issue by sebas5384** [choko-org/redux-boot#31]
Need to update the handleAction to use the defaultState.
https://github.com/acdlite/redux-actions/pull/127

Workaround for this bug is locking the peerDependencies to 0.13.0.

`"redux-actions": "0.13.0",`

**Comment by arojunior** [comment]
What if you just pass an empty object as second parameter?

["The second parameter defaultState is required, and is used when undefined is passed to the reducer."](https://github.com/acdlite/redux-actions#handleactionsreducermap-defaultstate)

Knowing that, the second parameter will never be used in redux-boot... It's created by a map function.
