### ISSUE TITLE
Example test failing

### ISSUE THREAD

**Issue by arojunior** [choko-org/redux-boot#32]
Example with a simple reducer and an async middleware (Spotify API)

{ error: { status: 401, message: 'No token provided' } } 'Unauthorized'

✖ A side-effect of BOOT action modified the state using a middleware and reducer handler.

operator: equal
      expected: 'Led Zeppelin'
      actual:   ''
      at: Test.assert [as _assert] (/Users/arojunior/Dropbox/compartilhado/Github/redux-boot/build/test.js:1199:18)

**Comment by sebas5384** [comment]
@arojunior great catch! I suppose when the #33 PR is merged this issue is gone, right?
